language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
sudo: required
services:
 - docker
notifications:
  email:
  - breedis+travis@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
    - master
env:
  global:
  # Remove for conciseness
before_install:
  - gem install travis -v 1.8.5 --no-rdoc --no-ri
  - sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
  - sudo chmod +x /usr/local/bin/ecs-cli
  - export BUILD_NAME=ses-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
  - export CONTAINER_IP=52.53.169.60
  - export PLATFORM_TEST_NAME="ses-platform-tests"
script:
  - sh infrastructure/travis/scripts/build.sh
  - sh infrastructure/travis/scripts/deploy_images.sh